services:
    web:
        image: nginx:1.24.0
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html

    app:
        build:
            context: ./docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    db:
        image: postgres:16.0
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 54323:5432
        #volumes:
            #- ./docker/postgres/data:/var/lib/postgresql/data

   # node:
     #   build:
    #        context: ./docker/node
      #      dockerfile: Dockerfile.node
      #  volumes:
          #  - .:/var/www/html
       # command: npm run dev
